name: aichat
description: aichat

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.14
  uuid: ^3.0.7
  http: ^0.13.5
  sp_util: ^2.0.3
  shared_preferences: ^2.0.18
  intl: ^0.18.0
  dart_openai: ^1.8.0
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.10
  share_plus: ^6.3.1
  rating_dialog: ^2.0.4
  lottie: ^2.2.0
  provider: ^6.0.5
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - images/

